// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4GCphTprMhcXPDJlwo3UgNpJkutov7lo',
    appId: '1:523588175031:web:dd91bc12f3d9ac87bbb932',
    messagingSenderId: '523588175031',
    projectId: 'firearmappraiser',
    authDomain: 'firearmappraiser.firebaseapp.com',
    storageBucket: 'firearmappraiser.firebasestorage.app',
    measurementId: 'G-WW9L1BE6CP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtqiiw6l6zWnbcjlCPZCq4c2GUezLDW-M',
    appId: '1:523588175031:android:15dc3b5c69734a23bbb932',
    messagingSenderId: '523588175031',
    projectId: 'firearmappraiser',
    storageBucket: 'firearmappraiser.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_Ausc7Q3KM60IkqfmNev1tfKhgJvC7eA',
    appId: '1:523588175031:ios:0367c9d426b324a0bbb932',
    messagingSenderId: '523588175031',
    projectId: 'firearmappraiser',
    storageBucket: 'firearmappraiser.firebasestorage.app',
    iosBundleId: 'com.operator.appraisalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_Ausc7Q3KM60IkqfmNev1tfKhgJvC7eA',
    appId: '1:523588175031:ios:0367c9d426b324a0bbb932',
    messagingSenderId: '523588175031',
    projectId: 'firearmappraiser',
    storageBucket: 'firearmappraiser.firebasestorage.app',
    iosBundleId: 'com.operator.appraisalApp',
  );
}
